name: Pre-Commit

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Add uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --dev

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
